### ISSUE TITLE
Printer friendly colors

### ISSUE THREAD

**Issue by ccolombo** [mnishihan/laravel-docs-in-pdf#1]
Hi, awesome PDFs!
The problem is when trying to print on paper. The code snipets with black background came out almost solid-black. 
It would be good to somehow have printer friendly version available.

**Comment by mnishihan** [comment]
@ccolombo Thanks for pointing this out. I've updated the colour scheme for code blocks to light mode. You may try now.

**Comment by mnishihan** [comment]
Closing this issue now. Feel free to reopen, if any issues are found.
